### ISSUE TITLE
daySize property not being used

### ISSUE THREAD

**Issue by nikolaceh** [larixsource/angular-react-dates#3]
As per title, the daySize property is not being observed.
http://prntscr.com/gbl0qv - see screenshot of React inspector tools showing discrepancy between set parameter and actual used size.

**Comment by eldarsil** [comment]
Hi @nikolaceh! Thanks for the heads up! I'll check that and fix it soon.

**Comment by eldarsil** [comment]
Hi @nikolaceh. Now it's fixed. The react-dates dependencies have been updated and daySize property was added (among others). Please check demo page and update your dependency version to 0.1.5.

**Comment by ghost** [comment]
Wonderful :) daySize works, I'll probably check out others as well soon.
Thank you for the quick response
